name: flutter_braintree
description: Flutter plugin that wraps the native Braintree SDKs. Enables payments with credit cards, PayPal, Google Pay and more.
version: 3.0.0
homepage: https://github.com/masnun-siam/flutter-braintree

environment:
  sdk: "3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_braintree
        pluginClass: FlutterBraintreePlugin
      ios:
        pluginClass: FlutterBraintreePlugin
